#!/usr/bin/env npx tsx
import fs from 'fs';
import path from 'path';

type Command = readonly ['M' | 'L', number, number] | 'Z';

const COMMANDS: readonly Command[] = [
  ['M', 1, 0],
  ['L', 1, 15],
  ['L', 7, 15],
  ['L', 7, 11],
  ['L', 9, 11],
  ['L', 9, 15],
  ['L', 13, 15],
  ['L', 13, 17],
  ['L', 0, 17],
  ['L', 0, 19],
  ['L', 15, 19],
  ['L', 15, 13],
  ['L', 11, 13],
  ['L', 11, 11],
  ['L', 15, 11],
  ['L', 15, 7],
  ['L', 17, 7],
  ['L', 17, 20],
  ['L', 17, 33],
  ['L', 15, 33],
  ['L', 15, 29],
  ['L', 11, 29],
  ['L', 11, 27],
  ['L', 15, 27],
  ['L', 15, 21],
  ['L', 0, 21],
  ['L', 0, 23],
  ['L', 13, 23],
  ['L', 13, 25],
  ['L', 9, 25],
  ['L', 9, 29],
  ['L', 7, 29],
  ['L', 7, 25],
  ['L', 1, 25],
  ['L', 1, 40],
  ['L', 3, 40],
  ['L', 3, 27],
  ['L', 5, 27],
  ['L', 5, 31],
  ['L', 9, 31],
  ['L', 9, 33],
  ['L', 5, 33],
  ['L', 5, 39],
  ['L', 20, 39],
  ['L', 35, 39],
  ['L', 35, 33],
  ['L', 31, 33],
  ['L', 31, 31],
  ['L', 35, 31],
  ['L', 35, 27],
  ['L', 37, 27],
  ['L', 37, 40],
  ['L', 39, 40],
  ['L', 39, 25],
  ['L', 33, 25],
  ['L', 33, 29],
  ['L', 31, 29],
  ['L', 31, 25],
  ['L', 27, 25],
  ['L', 27, 23],
  ['L', 40, 23],
  ['L', 40, 21],
  ['L', 25, 21],
  ['L', 25, 27],
  ['L', 29, 27],
  ['L', 29, 29],
  ['L', 25, 29],
  ['L', 25, 33],
  ['L', 23, 33],
  ['L', 23, 20],
  ['L', 23, 7],
  ['L', 25, 7],
  ['L', 25, 11],
  ['L', 29, 11],
  ['L', 29, 13],
  ['L', 25, 13],
  ['L', 25, 19],
  ['L', 40, 19],
  ['L', 40, 17],
  ['L', 27, 17],
  ['L', 27, 15],
  ['L', 31, 15],
  ['L', 31, 11],
  ['L', 33, 11],
  ['L', 33, 15],
  ['L', 39, 15],
  ['L', 39, 0],
  ['L', 37, 0],
  ['L', 37, 13],
  ['L', 35, 13],
  ['L', 35, 9],
  ['L', 31, 9],
  ['L', 31, 7],
  ['L', 35, 7],
  ['L', 35, 1],
  ['L', 20, 1],
  ['L', 5, 1],
  ['L', 5, 7],
  ['L', 9, 7],
  ['L', 9, 9],
  ['L', 5, 9],
  ['L', 5, 13],
  ['L', 3, 13],
  ['L', 3, 0],
  'Z',
  ['M', 7, 3],
  ['L', 20, 3],
  ['L', 33, 3],
  ['L', 33, 5],
  ['L', 29, 5],
  ['L', 29, 9],
  ['L', 27, 9],
  ['L', 27, 5],
  ['L', 21, 5],
  ['L', 21, 20],
  ['L', 21, 35],
  ['L', 27, 35],
  ['L', 27, 31],
  ['L', 29, 31],
  ['L', 29, 35],
  ['L', 33, 35],
  ['L', 33, 37],
  ['L', 20, 37],
  ['L', 7, 37],
  ['L', 7, 35],
  ['L', 11, 35],
  ['L', 11, 31],
  ['L', 13, 31],
  ['L', 13, 35],
  ['L', 19, 35],
  ['L', 19, 20],
  ['L', 19, 5],
  ['L', 13, 5],
  ['L', 13, 9],
  ['L', 11, 9],
  ['L', 11, 5],
  ['L', 7, 5],
  'Z',
] as const;

const STEP = 4;
const STROKE_WIDTH = 2;
const STROKE_COLOR = '#d4c9a8';
const OUTPUT_PATH = path.join(process.cwd(), 'public/patterns/sayagata.svg');

function buildPath(commands: readonly Command[], step: number): string {
  return commands
    .map((command) => {
      if (command === 'Z') {
        return 'Z';
      }
      const [cmd, x, y] = command;
      return `${cmd}${x * step},${y * step}`;
    })
    .join(' ');
}

function getTileSize(commands: readonly Command[], step: number): number {
  let max = 0;
  commands.forEach((command) => {
    if (command === 'Z') {
      return;
    }
    const [, x, y] = command;
    max = Math.max(max, x, y);
  });
  return max * step;
}

function buildSvg(pathData: string, size: number): string {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">`,
    '  <!-- Generated by scripts/docs/generate-sayagata.ts -->',
    `  <path d="${pathData}" fill="none" stroke="${STROKE_COLOR}" stroke-width="${STROKE_WIDTH}" stroke-linecap="square" stroke-linejoin="miter" />`,
    '</svg>',
    '',
  ].join('\n');
}

const pathData = buildPath(COMMANDS, STEP);
const tileSize = getTileSize(COMMANDS, STEP);
const svg = buildSvg(pathData, tileSize);

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, svg, 'utf8');
console.log(`Generated ${OUTPUT_PATH}`);
