import { spawn, type StdioOptions } from 'node:child_process';
import { promises as fs, constants as fsConstants } from 'node:fs';
import path from 'node:path';

export type VerifierStatus = 'success' | 'failed' | 'dev_mode';

export interface VerifierInvocationOptions {
  bundlePath: string;
  expectedImageId: string;
  reportPath: string;
  binaryPath?: string;
  /**
   * Optional spawn implementation (primarily for tests).
   */
  spawnImpl?: SpawnImpl;
}

export interface VerificationReport {
  [key: string]: unknown;
  status: VerifierStatus;
  verifier_version: string;
  verified_at: string;
  duration_ms: number;
  expected_image_id: string;
  receipt_image_id: string | null;
  bundle_path: string;
  receipt_path: string;
  dev_mode_receipt: boolean;
  errors?: string[];
}

export interface VerifierInvocationResult {
  status: VerifierStatus;
  reportPath: string;
  bundlePath: string;
  report: VerificationReport;
}

export interface SpawnOptions {
  stdio: StdioOptions;
  env?: NodeJS.ProcessEnv;
}

export interface SpawnedProcess {
  stdout: NodeJS.ReadableStream | null;
  stderr: NodeJS.ReadableStream | null;
  on(event: 'error', listener: (error: Error) => void): void;
  on(event: 'close', listener: (code: number | null) => void): void;
}

export type SpawnImpl = (command: string, args: readonly string[], options: SpawnOptions) => SpawnedProcess;

export async function invokeVerifierService(options: VerifierInvocationOptions): Promise<VerifierInvocationResult> {
  const binaryPath = await resolveBinaryPath(options.binaryPath);

  await fs.mkdir(path.dirname(options.reportPath), { recursive: true });

  const args = [
    'verify',
    '--bundle',
    options.bundlePath,
    '--image-id',
    options.expectedImageId,
    '--output',
    options.reportPath,
  ];

  const spawnFn: SpawnImpl =
    options.spawnImpl ??
    ((command, args, spawnOptions) => {
      return spawn(command, args, spawnOptions);
    });
  const child = spawnFn(binaryPath, args, {
    stdio: ['ignore', 'pipe', 'pipe'],
    env: {
      ...process.env,
    },
  });

  let stdout = '';
  let stderr = '';

  const appendChunk = (chunk: unknown): string => {
    if (typeof chunk === 'string') {
      return chunk;
    }
    if (Buffer.isBuffer(chunk)) {
      return chunk.toString('utf-8');
    }
    return String(chunk);
  };

  if (!child.stdout || !child.stderr) {
    throw new Error('verifier-service did not provide stdout/stderr streams');
  }

  child.stdout.on('data', (data: unknown) => {
    stdout += appendChunk(data);
  });

  child.stderr.on('data', (data: unknown) => {
    stderr += appendChunk(data);
  });

  const exitCode: number | null = await new Promise((resolve, reject) => {
    child.on('error', reject);
    child.on('close', (code) => resolve(code));
  });

  if (exitCode === null) {
    throw new Error('verifier-service did not exit cleanly');
  }

  if (exitCode === 1) {
    throw new Error(stderr.trim() || 'verifier-service exited with status 1 (general error)');
  }

  const report = await readVerificationReport(options.reportPath, stdout);

  return {
    status: report.status,
    reportPath: options.reportPath,
    bundlePath: options.bundlePath,
    report,
  };
}

async function resolveBinaryPath(explicitPath?: string): Promise<string> {
  const candidates = [
    explicitPath,
    process.env.VERIFIER_SERVICE_BIN,
    path.join(process.cwd(), 'verifier-service', 'target', 'release', 'verifier-service'),
    path.join(process.cwd(), 'verifier-service', 'target', 'debug', 'verifier-service'),
  ].filter(Boolean) as string[];

  for (const candidate of candidates) {
    try {
      await fs.access(candidate, fsConstants.X_OK);
      return candidate;
    } catch {
      // continue searching
    }
  }

  throw new Error('verifier-service binary not found. Set VERIFIER_SERVICE_BIN or build the project.');
}

async function readVerificationReport(reportPath: string, fallbackStdout: string): Promise<VerificationReport> {
  try {
    const content = await fs.readFile(reportPath, 'utf-8');
    return JSON.parse(content) as VerificationReport;
  } catch {
    if (fallbackStdout.trim().length > 0) {
      return JSON.parse(fallbackStdout) as VerificationReport;
    }
    throw new Error('verification report not generated by verifier-service');
  }
}
