/**
 * Vote ID Generation and Validation
 *
 * Implements UUID v4 (128-bit random) generation for unique vote tracking.
 * Provides cryptographically secure vote identifiers that are:
 * - Unpredictable: Cannot guess other vote IDs
 * - Unique: Extremely low collision probability (2^128 space)
 * - Verifiable: Can validate format and track generation
 */

import { randomUUID } from 'crypto';

/**
 * Generate a new UUID v4 vote identifier
 *
 * Uses crypto.randomUUID() which provides:
 * - Cryptographically secure randomness
 * - RFC 4122 compliant UUID v4 format
 * - 128 bits of entropy
 *
 * @returns A new UUID v4 string
 */
export function generateVoteId(): string {
  try {
    return randomUUID();
  } catch (error) {
    // This should rarely happen in modern Node.js environments
    throw new Error(`Failed to generate vote ID: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Validate if a string is a valid vote ID
 *
 * Checks for:
 * - Valid UUID v4 format
 * - No path traversal attempts
 * - Proper length and character set
 *
 * @param voteId - The vote ID to validate
 * @returns true if valid, false otherwise
 */
export function isValidVoteId(voteId: string): boolean {
  // Security: Prevent path traversal attacks
  if (voteId.includes('..') || voteId.includes('/') || voteId.includes('\\')) {
    return false;
  }

  // UUID v4 validation regex
  // Format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
  // where y is one of [8, 9, a, b]
  const uuidV4Regex = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

  return uuidV4Regex.test(voteId);
}

/**
 * Vote ID Generator with tracking capabilities
 *
 * Provides additional features beyond simple generation:
 * - Tracks all generated IDs
 * - Records generation timestamps
 * - Supports clearing history
 * - Useful for testing and auditing
 */
export class VoteIdGenerator {
  private generatedIds: Map<string, number>;

  constructor() {
    this.generatedIds = new Map();
  }

  /**
   * Generate a new vote ID and track it
   *
   * @returns A new UUID v4 string
   */
  generate(): string {
    const voteId = generateVoteId();
    this.generatedIds.set(voteId, Date.now());
    return voteId;
  }

  /**
   * Check if a vote ID was generated by this instance
   *
   * @param voteId - The vote ID to check
   * @returns true if generated by this instance
   */
  hasGenerated(voteId: string): boolean {
    return this.generatedIds.has(voteId);
  }

  /**
   * Get the number of IDs generated
   *
   * @returns The count of generated IDs
   */
  getCount(): number {
    return this.generatedIds.size;
  }

  /**
   * Clear all tracked IDs
   */
  clear(): void {
    this.generatedIds.clear();
  }

  /**
   * Get the timestamp when an ID was generated
   *
   * @param voteId - The vote ID to check
   * @returns The timestamp or undefined if not found
   */
  getTimestamp(voteId: string): number | undefined {
    return this.generatedIds.get(voteId);
  }
}
